/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerNav?: Array<{
    label: string;
    href?: string;
    children?: Array<{
      label: string;
      href: string;
      _key: string;
    }>;
    _type: "navItem";
    _key: string;
  }>;
  footerColumns?: Array<{
    title: string;
    links?: Array<{
      label: string;
      href: string;
      isExternal?: boolean;
      _key: string;
    }>;
    _type: "footerColumn";
    _key: string;
  }>;
  legalLinks?: Array<{
    label: string;
    href: string;
    _key: string;
  }>;
  socialLinks?: Array<{
    platform:
      | "twitter"
      | "instagram"
      | "facebook"
      | "linkedin"
      | "youtube"
      | "substack";
    url: string;
    label?: string;
    _key: string;
  }>;
};

export type SharedContent = {
  _id: string;
  _type: "sharedContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  statistics?: Array<{
    key?: string;
    number: string;
    label: string;
    description: string;
    _key: string;
  }>;
  primaryCTA?: {
    label: string;
    href: string;
  };
  donateCTA?: {
    label: string;
    href: string;
  };
  copyrightText?: string;
  nonprofitDisclaimer?: string;
  privacyNotice?: string;
};

export type NewsletterSettings = {
  _id: string;
  _type: "newsletterSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stripHeadline: string;
  stripSubheadline?: string;
  sectionTitle: string;
  sectionDescription?: string;
  nameLabel?: string;
  emailLabel?: string;
  emailPlaceholder?: string;
  substackCheckboxLabel?: string;
  substackCheckboxHint?: string;
  legalNotice?: string;
  buttonDefault?: string;
  buttonLoading?: string;
  buttonSuccess?: string;
  errorNameRequired?: string;
  errorEmailInvalid?: string;
  errorGeneric?: string;
};

export type PressPageSettings = {
  _id: string;
  _type: "pressPageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSubtitle: string;
  heroTitle: string;
  heroDescription?: string;
};

export type FaqPageSettings = {
  _id: string;
  _type: "faqPageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSubtitle: string;
  heroTitle: string;
  contactCTAText?: string;
  contactCTAHref?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type JoinPageSettings = {
  _id: string;
  _type: "joinPageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSubtitle?: string;
  heroTitle: string;
  heroDescription?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  veteranCard?: {
    title?: string;
    description?: string;
    buttonText?: string;
  };
  advocateCard?: {
    title?: string;
    description?: string;
    buttonText?: string;
  };
  memberTypeOptions?: Array<{
    value?: string;
    label?: string;
    _key: string;
  }>;
  veteranSuccessTitle?: string;
  veteranSuccessMessage?: string;
  advocateSuccessTitle?: string;
  advocateSuccessMessage?: string;
  privacyText?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type ContactPageSettings = {
  _id: string;
  _type: "contactPageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSubtitle?: string;
  heroTitle: string;
  heroDescription?: string;
  contactEmail: string;
  contactPanelHeadline?: string;
  socialLinks?: Array<{
    platform?: string;
    handle?: string;
    url?: string;
    _key: string;
  }>;
  formTitle?: string;
  topicOptions?: Array<{
    value?: string;
    label?: string;
    _key: string;
  }>;
  successTitle?: string;
  successMessage?: string;
};

export type OurWorkPageSettings = {
  _id: string;
  _type: "ourWorkPageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSubtitle?: string;
  heroTitle: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroImageAlt?: string;
  mainVideoUrl?: string;
  caseForRepairIntro?: Array<string>;
  statistics?: Array<{
    number: string;
    label: string;
    description: string;
    _key: string;
  }>;
  caseForRepairContinued?: Array<string>;
  howRepairHappensTitle?: string;
  howRepairHappensIntro?: string;
  repairBulletPoints?: Array<string>;
  theoryOfChangeTitle?: string;
  theoryOfChangeIntro?: string;
  litigationTitle?: string;
  litigationVideoUrl?: string;
  litigationParagraphs?: Array<string>;
  litigationCTA?: {
    title?: string;
    buttonText?: string;
    href?: string;
  };
  narrativeTitle?: string;
  narrativeParagraphs?: Array<string>;
  narrativeCTA?: {
    title?: string;
    buttonText?: string;
    href?: string;
    isExternal?: boolean;
  };
  mobilizationTitle?: string;
  mobilizationParagraphs?: Array<string>;
  mobilizationCTA?: {
    title?: string;
    buttonText?: string;
    href?: string;
  };
};

export type DonatePageSettings = {
  _id: string;
  _type: "donatePageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSubtitle?: string;
  heroTitle: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mainParagraphs?: Array<string>;
  taxNoticeTitle?: string;
  taxNoticeText?: string;
  donationFormUrl: string;
  recurringDonationText?: string;
};

export type AboutPageSettings = {
  _id: string;
  _type: "aboutPageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSubtitle?: string;
  heroTitle: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroImageAlt?: string;
  missionParagraphs?: Array<string>;
  nonprofitText?: string;
  timelineTitle?: string;
  timelineEvents?: Array<{
    year: string;
    title: string;
    description: string;
    _key: string;
  }>;
  pressCTATitle?: string;
  pressCTAText?: string;
  featuredInLogos?: Array<string>;
};

export type HomepageSettings = {
  _id: string;
  _type: "homepageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeadline: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ourWorkTitle?: string;
  ourWorkIntro?: string;
  pillars?: Array<{
    title: string;
    description: string;
    cta: string;
    href: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    imageAlt?: string;
    _key: string;
  }>;
  newsletterHeadline?: string;
  newsletterSubheadline?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tagline?: string;
  heroHeadline?: string;
  contactEmail?: string;
  socialLinks?: {
    twitter?: string;
    instagram?: string;
    facebook?: string;
    linkedin?: string;
    youtube?: string;
  };
  footerText?: string;
};

export type SubstackArticle = {
  _id: string;
  _type: "substackArticle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
  substackUrl: string;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt: string;
  isFeatured?: boolean;
  displayOrder?: number;
  isVisible?: boolean;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: string;
  category: "about" | "involvement" | "donations" | "programs";
  order?: number;
};

export type Press = {
  _id: string;
  _type: "press";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  date: string;
  source: string;
  author?: string;
  url?: string;
  type?: "news" | "opinion" | "broadcast";
  topics?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt?: string;
  featured?: boolean;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  category: "partner" | "sponsor" | "funder" | "media";
  order?: number;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  category: "founder" | "leadership" | "team" | "board" | "advisor";
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  email?: string;
  linkedin?: string;
  initials?: string;
  order?: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroHeadline?: string;
  heroSubheadline?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  seoDescription?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Navigation
  | SharedContent
  | NewsletterSettings
  | PressPageSettings
  | FaqPageSettings
  | SanityImageAssetReference
  | JoinPageSettings
  | SanityImageCrop
  | SanityImageHotspot
  | ContactPageSettings
  | OurWorkPageSettings
  | DonatePageSettings
  | AboutPageSettings
  | HomepageSettings
  | SiteSettings
  | SubstackArticle
  | Faq
  | Press
  | Partner
  | TeamMember
  | Page
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: teamMembersQuery
// Query: *[_type == "teamMember"] | order(order asc) {    _id,    name,    role,    category,    bio,    initials,    linkedin,    "photo": photo.asset->url  }
export type TeamMembersQueryResult = Array<{
  _id: string;
  name: string;
  role: string;
  category: "advisor" | "board" | "founder" | "leadership" | "team";
  bio: string | null;
  initials: string | null;
  linkedin: string | null;
  photo: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: partnersQuery
// Query: *[_type == "partner"] | order(order asc) {    _id,    name,    website,    category,    "logo": logo.asset->url  }
export type PartnersQueryResult = Array<{
  _id: string;
  name: string;
  website: string | null;
  category: "funder" | "media" | "partner" | "sponsor";
  logo: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: pressQuery
// Query: *[_type == "press"] | order(date desc) {    _id,    title,    date,    source,    author,    url,    type,    topics,    excerpt,    featured,    "image": image.asset->url  }
export type PressQueryResult = Array<{
  _id: string;
  title: string;
  date: string;
  source: string;
  author: string | null;
  url: string | null;
  type: "broadcast" | "news" | "opinion" | null;
  topics: Array<string> | null;
  excerpt: string | null;
  featured: boolean | null;
  image: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: featuredPressQuery
// Query: *[_type == "press" && featured == true] | order(date desc)[0...3] {    _id,    title,    date,    source,    url,    excerpt,    "image": image.asset->url  }
export type FeaturedPressQueryResult = Array<{
  _id: string;
  title: string;
  date: string;
  source: string;
  url: string | null;
  excerpt: string | null;
  image: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: faqsQuery
// Query: *[_type == "faq"] | order(order asc) {    _id,    question,    answer,    category  }
export type FaqsQueryResult = Array<{
  _id: string;
  question: string;
  answer: string;
  category: "about" | "donations" | "involvement" | "programs";
}>;

// Source: src/sanity/lib/queries.ts
// Variable: faqsByCategoryQuery
// Query: *[_type == "faq"] | order(order asc) {    _id,    question,    answer,    category  }
export type FaqsByCategoryQueryResult = Array<{
  _id: string;
  question: string;
  answer: string;
  category: "about" | "donations" | "involvement" | "programs";
}>;

// Source: src/sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    siteName,    tagline,    heroHeadline,    contactEmail,    footerText,    "logo": logo.asset->url,    socialLinks {      twitter,      instagram,      facebook,      linkedin,      youtube    }  }
export type SiteSettingsQueryResult = {
  siteName: string;
  tagline: string | null;
  heroHeadline: string | null;
  contactEmail: string | null;
  footerText: string | null;
  logo: string | null;
  socialLinks: {
    twitter: string | null;
    instagram: string | null;
    facebook: string | null;
    linkedin: string | null;
    youtube: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    heroHeadline,    heroSubheadline,    "heroImage": heroImage.asset->url,    content,    seoDescription  }
export type PageBySlugQueryResult = {
  _id: string;
  title: string;
  slug: string;
  heroHeadline: string | null;
  heroSubheadline: string | null;
  heroImage: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  seoDescription: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: allPagesQuery
// Query: *[_type == "page"] {    _id,    title,    "slug": slug.current  }
export type AllPagesQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: homepageSettingsQuery
// Query: *[_type == "homepageSettings"][0] {    heroHeadline,    "heroImage": heroImage.asset->url,    ourWorkTitle,    ourWorkIntro,    pillars[] {      title,      description,      cta,      href,      "image": image.asset->url,      imageAlt    },    newsletterHeadline,    newsletterSubheadline  }
export type HomepageSettingsQueryResult = {
  heroHeadline: string;
  heroImage: string | null;
  ourWorkTitle: string | null;
  ourWorkIntro: string | null;
  pillars: Array<{
    title: string;
    description: string;
    cta: string;
    href: string;
    image: string | null;
    imageAlt: string | null;
  }> | null;
  newsletterHeadline: string | null;
  newsletterSubheadline: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: aboutPageSettingsQuery
// Query: *[_type == "aboutPageSettings"][0] {    heroSubtitle,    heroTitle,    "heroImage": heroImage.asset->url,    heroImageAlt,    missionParagraphs,    nonprofitText,    timelineTitle,    timelineEvents[] {      year,      title,      description    },    pressCTATitle,    pressCTAText,    featuredInLogos  }
export type AboutPageSettingsQueryResult = {
  heroSubtitle: string | null;
  heroTitle: string;
  heroImage: string | null;
  heroImageAlt: string | null;
  missionParagraphs: Array<string> | null;
  nonprofitText: string | null;
  timelineTitle: string | null;
  timelineEvents: Array<{
    year: string;
    title: string;
    description: string;
  }> | null;
  pressCTATitle: string | null;
  pressCTAText: string | null;
  featuredInLogos: Array<string> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: donatePageSettingsQuery
// Query: *[_type == "donatePageSettings"][0] {    heroSubtitle,    heroTitle,    "heroImage": heroImage.asset->url,    mainParagraphs,    taxNoticeTitle,    taxNoticeText,    donationFormUrl,    recurringDonationText  }
export type DonatePageSettingsQueryResult = {
  heroSubtitle: string | null;
  heroTitle: string;
  heroImage: string | null;
  mainParagraphs: Array<string> | null;
  taxNoticeTitle: string | null;
  taxNoticeText: string | null;
  donationFormUrl: string;
  recurringDonationText: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ourWorkPageSettingsQuery
// Query: *[_type == "ourWorkPageSettings"][0] {    heroSubtitle,    heroTitle,    "heroImage": heroImage.asset->url,    heroImageAlt,    mainVideoUrl,    caseForRepairIntro,    statistics[] {      number,      label,      description    },    caseForRepairContinued,    howRepairHappensTitle,    howRepairHappensIntro,    repairBulletPoints,    theoryOfChangeTitle,    theoryOfChangeIntro,    litigationTitle,    litigationVideoUrl,    litigationParagraphs,    litigationCTA {      title,      buttonText,      href    },    narrativeTitle,    narrativeParagraphs,    narrativeCTA {      title,      buttonText,      href,      isExternal    },    mobilizationTitle,    mobilizationParagraphs,    mobilizationCTA {      title,      buttonText,      href    }  }
export type OurWorkPageSettingsQueryResult = {
  heroSubtitle: string | null;
  heroTitle: string;
  heroImage: string | null;
  heroImageAlt: string | null;
  mainVideoUrl: string | null;
  caseForRepairIntro: Array<string> | null;
  statistics: Array<{
    number: string;
    label: string;
    description: string;
  }> | null;
  caseForRepairContinued: Array<string> | null;
  howRepairHappensTitle: string | null;
  howRepairHappensIntro: string | null;
  repairBulletPoints: Array<string> | null;
  theoryOfChangeTitle: string | null;
  theoryOfChangeIntro: string | null;
  litigationTitle: string | null;
  litigationVideoUrl: string | null;
  litigationParagraphs: Array<string> | null;
  litigationCTA: {
    title: string | null;
    buttonText: string | null;
    href: string | null;
  } | null;
  narrativeTitle: string | null;
  narrativeParagraphs: Array<string> | null;
  narrativeCTA: {
    title: string | null;
    buttonText: string | null;
    href: string | null;
    isExternal: boolean | null;
  } | null;
  mobilizationTitle: string | null;
  mobilizationParagraphs: Array<string> | null;
  mobilizationCTA: {
    title: string | null;
    buttonText: string | null;
    href: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: contactPageSettingsQuery
// Query: *[_type == "contactPageSettings"][0] {    heroSubtitle,    heroTitle,    heroDescription,    contactEmail,    contactPanelHeadline,    socialLinks[] {      platform,      handle,      url    },    formTitle,    topicOptions[] {      value,      label    },    successTitle,    successMessage  }
export type ContactPageSettingsQueryResult = {
  heroSubtitle: string | null;
  heroTitle: string;
  heroDescription: string | null;
  contactEmail: string;
  contactPanelHeadline: string | null;
  socialLinks: Array<{
    platform: string | null;
    handle: string | null;
    url: string | null;
  }> | null;
  formTitle: string | null;
  topicOptions: Array<{
    value: string | null;
    label: string | null;
  }> | null;
  successTitle: string | null;
  successMessage: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: joinPageSettingsQuery
// Query: *[_type == "joinPageSettings"][0] {    heroSubtitle,    heroTitle,    heroDescription,    "heroImage": heroImage.asset->url,    veteranCard {      title,      description,      buttonText    },    advocateCard {      title,      description,      buttonText    },    memberTypeOptions[] {      value,      label    },    veteranSuccessTitle,    veteranSuccessMessage,    advocateSuccessTitle,    advocateSuccessMessage,    privacyText  }
export type JoinPageSettingsQueryResult = {
  heroSubtitle: string | null;
  heroTitle: string;
  heroDescription: string | null;
  heroImage: string | null;
  veteranCard: {
    title: string | null;
    description: string | null;
    buttonText: string | null;
  } | null;
  advocateCard: {
    title: string | null;
    description: string | null;
    buttonText: string | null;
  } | null;
  memberTypeOptions: Array<{
    value: string | null;
    label: string | null;
  }> | null;
  veteranSuccessTitle: string | null;
  veteranSuccessMessage: string | null;
  advocateSuccessTitle: string | null;
  advocateSuccessMessage: string | null;
  privacyText: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: substackArticlesQuery
// Query: *[_type == "substackArticle" && isVisible == true] | order(displayOrder asc, publishedAt desc) {    _id,    title,    description,    substackUrl,    "featuredImage": featuredImage.asset->url,    publishedAt,    isFeatured,    displayOrder  }
export type SubstackArticlesQueryResult = Array<{
  _id: string;
  title: string;
  description: string | null;
  substackUrl: string;
  featuredImage: string | null;
  publishedAt: string;
  isFeatured: boolean | null;
  displayOrder: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: featuredSubstackArticleQuery
// Query: *[_type == "substackArticle" && isVisible == true && isFeatured == true][0] {    _id,    title,    description,    substackUrl,    "featuredImage": featuredImage.asset->url,    publishedAt  }
export type FeaturedSubstackArticleQueryResult = {
  _id: string;
  title: string;
  description: string | null;
  substackUrl: string;
  featuredImage: string | null;
  publishedAt: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: sharedContentQuery
// Query: *[_type == "sharedContent"][0] {    statistics[] {      key,      number,      label,      description    },    primaryCTA {      text,      href,      description    },    donateCTA {      text,      href,      description    },    copyrightText,    nonprofitDisclaimer,    privacyNotice  }
export type SharedContentQueryResult = {
  statistics: Array<{
    key: string | null;
    number: string;
    label: string;
    description: string;
  }> | null;
  primaryCTA: {
    text: null;
    href: string;
    description: null;
  } | null;
  donateCTA: {
    text: null;
    href: string;
    description: null;
  } | null;
  copyrightText: string | null;
  nonprofitDisclaimer: string | null;
  privacyNotice: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: navigationQuery
// Query: *[_type == "navigation"][0] {    headerNav[] {      label,      href,      children[] {        label,        href      }    },    footerColumns[] {      title,      links[] {        label,        href,        isExternal      }    },    legalLinks[] {      label,      href    },    socialLinks[] {      platform,      url,      label    }  }
export type NavigationQueryResult = {
  headerNav: Array<{
    label: string;
    href: string | null;
    children: Array<{
      label: string;
      href: string;
    }> | null;
  }> | null;
  footerColumns: Array<{
    title: string;
    links: Array<{
      label: string;
      href: string;
      isExternal: boolean | null;
    }> | null;
  }> | null;
  legalLinks: Array<{
    label: string;
    href: string;
  }> | null;
  socialLinks: Array<{
    platform:
      | "facebook"
      | "instagram"
      | "linkedin"
      | "substack"
      | "twitter"
      | "youtube";
    url: string;
    label: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: newsletterSettingsQuery
// Query: *[_type == "newsletterSettings"][0] {    stripHeadline,    stripSubheadline,    sectionTitle,    sectionDescription,    nameLabel,    emailLabel,    emailPlaceholder,    substackCheckboxLabel,    substackCheckboxHint,    legalNotice,    buttonDefault,    buttonLoading,    buttonSuccess,    errorNameRequired,    errorEmailInvalid,    errorGeneric  }
export type NewsletterSettingsQueryResult = {
  stripHeadline: string;
  stripSubheadline: string | null;
  sectionTitle: string;
  sectionDescription: string | null;
  nameLabel: string | null;
  emailLabel: string | null;
  emailPlaceholder: string | null;
  substackCheckboxLabel: string | null;
  substackCheckboxHint: string | null;
  legalNotice: string | null;
  buttonDefault: string | null;
  buttonLoading: string | null;
  buttonSuccess: string | null;
  errorNameRequired: string | null;
  errorEmailInvalid: string | null;
  errorGeneric: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: faqPageSettingsQuery
// Query: *[_type == "faqPageSettings"][0] {    heroSubtitle,    heroTitle,    contactCTAText,    contactCTAHref  }
export type FaqPageSettingsQueryResult = {
  heroSubtitle: string;
  heroTitle: string;
  contactCTAText: string | null;
  contactCTAHref: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: pressPageSettingsQuery
// Query: *[_type == "pressPageSettings"][0] {    heroSubtitle,    heroTitle,    heroDescription  }
export type PressPageSettingsQueryResult = {
  heroSubtitle: string;
  heroTitle: string;
  heroDescription: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "teamMember"] | order(order asc) {\n    _id,\n    name,\n    role,\n    category,\n    bio,\n    initials,\n    linkedin,\n    "photo": photo.asset->url\n  }\n': TeamMembersQueryResult;
    '\n  *[_type == "partner"] | order(order asc) {\n    _id,\n    name,\n    website,\n    category,\n    "logo": logo.asset->url\n  }\n': PartnersQueryResult;
    '\n  *[_type == "press"] | order(date desc) {\n    _id,\n    title,\n    date,\n    source,\n    author,\n    url,\n    type,\n    topics,\n    excerpt,\n    featured,\n    "image": image.asset->url\n  }\n': PressQueryResult;
    '\n  *[_type == "press" && featured == true] | order(date desc)[0...3] {\n    _id,\n    title,\n    date,\n    source,\n    url,\n    excerpt,\n    "image": image.asset->url\n  }\n': FeaturedPressQueryResult;
    '\n  *[_type == "faq"] | order(order asc) {\n    _id,\n    question,\n    answer,\n    category\n  }\n':
      | FaqsQueryResult
      | FaqsByCategoryQueryResult;
    '\n  *[_type == "siteSettings"][0] {\n    siteName,\n    tagline,\n    heroHeadline,\n    contactEmail,\n    footerText,\n    "logo": logo.asset->url,\n    socialLinks {\n      twitter,\n      instagram,\n      facebook,\n      linkedin,\n      youtube\n    }\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    heroHeadline,\n    heroSubheadline,\n    "heroImage": heroImage.asset->url,\n    content,\n    seoDescription\n  }\n': PageBySlugQueryResult;
    '\n  *[_type == "page"] {\n    _id,\n    title,\n    "slug": slug.current\n  }\n': AllPagesQueryResult;
    '\n  *[_type == "homepageSettings"][0] {\n    heroHeadline,\n    "heroImage": heroImage.asset->url,\n    ourWorkTitle,\n    ourWorkIntro,\n    pillars[] {\n      title,\n      description,\n      cta,\n      href,\n      "image": image.asset->url,\n      imageAlt\n    },\n    newsletterHeadline,\n    newsletterSubheadline\n  }\n': HomepageSettingsQueryResult;
    '\n  *[_type == "aboutPageSettings"][0] {\n    heroSubtitle,\n    heroTitle,\n    "heroImage": heroImage.asset->url,\n    heroImageAlt,\n    missionParagraphs,\n    nonprofitText,\n    timelineTitle,\n    timelineEvents[] {\n      year,\n      title,\n      description\n    },\n    pressCTATitle,\n    pressCTAText,\n    featuredInLogos\n  }\n': AboutPageSettingsQueryResult;
    '\n  *[_type == "donatePageSettings"][0] {\n    heroSubtitle,\n    heroTitle,\n    "heroImage": heroImage.asset->url,\n    mainParagraphs,\n    taxNoticeTitle,\n    taxNoticeText,\n    donationFormUrl,\n    recurringDonationText\n  }\n': DonatePageSettingsQueryResult;
    '\n  *[_type == "ourWorkPageSettings"][0] {\n    heroSubtitle,\n    heroTitle,\n    "heroImage": heroImage.asset->url,\n    heroImageAlt,\n    mainVideoUrl,\n    caseForRepairIntro,\n    statistics[] {\n      number,\n      label,\n      description\n    },\n    caseForRepairContinued,\n    howRepairHappensTitle,\n    howRepairHappensIntro,\n    repairBulletPoints,\n    theoryOfChangeTitle,\n    theoryOfChangeIntro,\n    litigationTitle,\n    litigationVideoUrl,\n    litigationParagraphs,\n    litigationCTA {\n      title,\n      buttonText,\n      href\n    },\n    narrativeTitle,\n    narrativeParagraphs,\n    narrativeCTA {\n      title,\n      buttonText,\n      href,\n      isExternal\n    },\n    mobilizationTitle,\n    mobilizationParagraphs,\n    mobilizationCTA {\n      title,\n      buttonText,\n      href\n    }\n  }\n': OurWorkPageSettingsQueryResult;
    '\n  *[_type == "contactPageSettings"][0] {\n    heroSubtitle,\n    heroTitle,\n    heroDescription,\n    contactEmail,\n    contactPanelHeadline,\n    socialLinks[] {\n      platform,\n      handle,\n      url\n    },\n    formTitle,\n    topicOptions[] {\n      value,\n      label\n    },\n    successTitle,\n    successMessage\n  }\n': ContactPageSettingsQueryResult;
    '\n  *[_type == "joinPageSettings"][0] {\n    heroSubtitle,\n    heroTitle,\n    heroDescription,\n    "heroImage": heroImage.asset->url,\n    veteranCard {\n      title,\n      description,\n      buttonText\n    },\n    advocateCard {\n      title,\n      description,\n      buttonText\n    },\n    memberTypeOptions[] {\n      value,\n      label\n    },\n    veteranSuccessTitle,\n    veteranSuccessMessage,\n    advocateSuccessTitle,\n    advocateSuccessMessage,\n    privacyText\n  }\n': JoinPageSettingsQueryResult;
    '\n  *[_type == "substackArticle" && isVisible == true] | order(displayOrder asc, publishedAt desc) {\n    _id,\n    title,\n    description,\n    substackUrl,\n    "featuredImage": featuredImage.asset->url,\n    publishedAt,\n    isFeatured,\n    displayOrder\n  }\n': SubstackArticlesQueryResult;
    '\n  *[_type == "substackArticle" && isVisible == true && isFeatured == true][0] {\n    _id,\n    title,\n    description,\n    substackUrl,\n    "featuredImage": featuredImage.asset->url,\n    publishedAt\n  }\n': FeaturedSubstackArticleQueryResult;
    '\n  *[_type == "sharedContent"][0] {\n    statistics[] {\n      key,\n      number,\n      label,\n      description\n    },\n    primaryCTA {\n      text,\n      href,\n      description\n    },\n    donateCTA {\n      text,\n      href,\n      description\n    },\n    copyrightText,\n    nonprofitDisclaimer,\n    privacyNotice\n  }\n': SharedContentQueryResult;
    '\n  *[_type == "navigation"][0] {\n    headerNav[] {\n      label,\n      href,\n      children[] {\n        label,\n        href\n      }\n    },\n    footerColumns[] {\n      title,\n      links[] {\n        label,\n        href,\n        isExternal\n      }\n    },\n    legalLinks[] {\n      label,\n      href\n    },\n    socialLinks[] {\n      platform,\n      url,\n      label\n    }\n  }\n': NavigationQueryResult;
    '\n  *[_type == "newsletterSettings"][0] {\n    stripHeadline,\n    stripSubheadline,\n    sectionTitle,\n    sectionDescription,\n    nameLabel,\n    emailLabel,\n    emailPlaceholder,\n    substackCheckboxLabel,\n    substackCheckboxHint,\n    legalNotice,\n    buttonDefault,\n    buttonLoading,\n    buttonSuccess,\n    errorNameRequired,\n    errorEmailInvalid,\n    errorGeneric\n  }\n': NewsletterSettingsQueryResult;
    '\n  *[_type == "faqPageSettings"][0] {\n    heroSubtitle,\n    heroTitle,\n    contactCTAText,\n    contactCTAHref\n  }\n': FaqPageSettingsQueryResult;
    '\n  *[_type == "pressPageSettings"][0] {\n    heroSubtitle,\n    heroTitle,\n    heroDescription\n  }\n': PressPageSettingsQueryResult;
  }
}
